# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# INFO ENDPOINT CONFIGURATION
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
info.app.name=@project.name@
info.app.description=@project.description@
info.app.version=@project.version@
info.app.encoding=@project.build.sourceEncoding@
info.app.java.version=@java.version@
info.app.builddate=@timestamp@

# SPRING
spring.datasource.url=jdbc:postgresql://localhost:5432/bep2
spring.datasource.username=bep2
spring.datasource.password=bep2
spring.datasource.dataSourceClassName=org.postgresql.Driver

bep.liquibase.datasource.changelog=classpath:/de/arvato/mybe/db/changelog/db.changelog.xml
bep.liquibase.datasource.enabled=true

server.port=9200
server.servlet.context-path=/becentral

sendMail.retry.max.attempts=3
email.queue.scheduler.cron =*/10 * * * * ?
spring.mail.host=cmail.servicemail24.de
spring.mail.port=587
spring.mail.username=dummy
spring.mail.password=dummy
spring.mail.properties.mail.smtp.port=587
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.enable=false
spring.mail.properties.mail.smtp.timeout=15000
spring.mail.properties.mail.smtp.connectiontimeout=15000
spring.mail.properties.mail.smtp.ssl.trust= smtp.office365.com
spring.mail.sendername=BEP-bot

# bouncr
#aep.security.bouncr.host=https://aepapimanagementtemp.azure-api.net/portal/consumer
#aep.security.bouncr.subscriptionKey=954805cd8c5b4869a8439928a4075a73
#aep.security.bouncr.instanceId=e4eeb1e3-6426-4053-acf2-5288c236fe8e
#OAuth2
#spring.security.oauth2.resourceserver.jwt.jwk-set-uri=https://aepfrontendtest.b2clogin.com/aepfrontendtest.onmicrosoft.com/b2c_1_signup-and-signin/discovery/v2.0/keys
aep.security.cors.pattern=*
aep.security.bouncr.enabled=false

# for local testing only
aep.security.auth-method=basic
aep.security.basicauth.users[0].username=bep
aep.security.basicauth.users[0].password=bep
aep.security.basicauth.users[0].rights=central.org.view,central.org.edit,central.employee.edit,central.employee.view,central.distributionlist.view,central.distributionlist.edit,central.holiday.view,central.holiday.edit
aep.security.basicauth.users[0].email=bot.my@bertelsmann.de
aep.security.basicauth.users[1].username=hr
aep.security.basicauth.users[1].password=hr
aep.security.basicauth.users[1].rights=central.org.view,central.org.edit,central.employee.view,central.employee.edit,central.distributionlist.view,central.distributionlist.edit
aep.security.basicauth.users[1].email=aharbottle2@army.mil
aep.security.basicauth.users[2].username=superior
aep.security.basicauth.users[2].password=superior
aep.security.basicauth.users[2].rights=central.org.view
aep.security.basicauth.users[2].email=aharbottle2@army.mil
aep.security.basicauth.users[3].username=staff
aep.security.basicauth.users[3].password=staff
aep.security.basicauth.users[3].rights=equal.task.edit
aep.security.basicauth.users[3].email=aharbottle2@army.mil
aep.security.basicauth.users[4].username=finance
aep.security.basicauth.users[4].password=finance
aep.security.basicauth.users[4].rights=central.org.view,central.org.edit,central.employee.view,central.distributionlist.view,central.distributionlist.edit
aep.security.basicauth.users[4].email=aharbottle2@army.mil

spring.main.allow-bean-definition-overriding=true

bep.central.employee.cache-in-seconds=60
bep.central.business.cache-in-minutes=2
bep.central.api-key=wEWfsrlKbgJv1c4qlHAbBEwXvVZ2Dvj0n6uBXXUDNkC2Xebqi3pdaRASXqTmfhj0DZtqDMr1IcxbrpPNOquZAaGd9UKdIjSY8pi4VoGwMYhrefGwD36NGsHkEMTp0Jh2
bep.central.admin.emails=bot.my@bertelsmann.de,choonkit.lai@bertelsmann.de
bep.central.rest.super-user-rights=central.employee.view,central.org.view,central.employee.edit,central.org.edit,central.holiday.view

bep.central.new-employee-notification.subject=Newly Created Employee List
bep.central.new-employee-notification.recipient=choonkit.lai@bertelsmann.de
bep.central.new-employee-notification.cron=0 * * * * ?
bep.central.new-employee-notification.window.minutes=10080
bep.central.new-employee-notification.enabled=false
